apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.siteName }}
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    app: {{ .Values.siteName }}

  ports:
  - port: 80
    targetPort: 80
