apiVersion: v1
kind: ResourceQuota

metadata:
  name: hosting-quota
  namespace: __NAMESPACE__

spec:
  hard:
    pods: "__PODS__"

    requests.cpu: "__REQUESTS_CPU__"
    requests.memory: "__REQUESTS_MEMORY__"

    limits.cpu: "__LIMITS_CPU__"
    limits.memory: "__LIMITS_MEMORY__"
